name: Feature Template
description: 기능 추가할 때 쓰는 템플릿
title: "✨ [Feat] "
labels: ["feature"]

body:
  - type: dropdown
    id: select-attribute
    attributes:
      label: "기능 종류"
      description: "어떤 기능을 추가하시나요?"
      options:
        - "기타"
        - "API 구현"
        - "설정 추가"
        - "내부 기능 구현"
    validations:
      required: true
  - type: input
    id: feature-content
    attributes:
      label: 어떤 기능을 추가하나요?
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. 게시글 조회 구현, 로그인 화면 구현
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: 자세한 내용 (Optional)
      description: 설명이 부족하다면 더 자세한 내용을 적어주세요.
      placeholder: ex. 게시글 조회에 커서 기반 페이지네이션 적용
    validations:
      required: false
